
name: Conda

on:
  push

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  conda_deployment_with_new_tag:
    name: Conda deployment of package for platform ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: env.yaml
          environment-name: build
          extra-specs: |
            python=${{ matrix.python-version }}
      - name: Build and upload the conda packages
        uses: gb119/action-build-and-upload-conda-packages@v0.1.5
        with:
          meta_yaml_dir: .
          overwrite: true
          python-version: ${{ matrix.python-version }} # Values previously defined in `matrix`
          mambabuild: true
          user: phygbu
          label: main
          token: ${{ secrets.ANACONDA }} # Replace with the right name of your secret
